# Generated by Django 5.2.4 on 2025-07-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('ready', 'Ready'), ('rejected', 'Rejected'), ('collected', 'Collected')], default='pending', max_length=20),
        ),
    ]
